from ..types import Buffer as Buffer, BufferType as BufferType
from .transform_link import TransformLink as TransformLink
from _typeshed import Incomplete

class TransformChain:
    links: list[TransformLink]
    buffer_type: Incomplete
    def __init__(self, buffer_type: BufferType) -> None: ...
    def add(self, link: TransformLink) -> None: ...
    def clear(self) -> None: ...
    def remove(self, link: TransformLink) -> None: ...
    def to_buffer(self) -> Buffer: ...
