from ..core.visual_base import VisualBase as VisualBase
from ..types.buffer import Buffer as Buffer
from ..types.group import Groups as Groups
from ..types.transbuf import TransBuf as TransBuf

class Pixels(VisualBase):
    def __init__(self, positions: TransBuf, colors: TransBuf, groups: Groups) -> None: ...
    def get_positions(self) -> TransBuf: ...
    def set_positions(self, positions: TransBuf) -> None: ...
    def get_colors(self) -> TransBuf: ...
    def set_colors(self, colors: TransBuf) -> None: ...
    def get_groups(self) -> Groups: ...
    def set_groups(self, groups: Groups) -> None: ...
    def set_attributes(self, positions: TransBuf | None = None, colors: TransBuf | None = None, groups: Groups | None = None) -> None: ...
    def check_attributes(self) -> None: ...
    @staticmethod
    def sanity_check_attributes_buffer(positions: Buffer, colors: Buffer, groups: Groups): ...
    @staticmethod
    def sanity_check_attributes(positions: TransBuf, colors: TransBuf, groups: Groups): ...
